name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dahlia/actions/yajsv@master
      with:
        schema: table.schema.yaml
        documents: tables/*.yaml
    - uses: zbeekman/EditorConfig-Action@master
    - uses: ibiqlik/action-yamllint@v3.0.0
      with:
        strict: yes

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - run: make -j validate-html5
